dist:
  xenial

language:
  c

compiler:
  gcc

matrix:
  include:
    - env:
      - SUITE=test
      - ABI=64
      - GAP=stable-4.10
      - PACKAGES=required

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-aaa.sh && scripts/travis-test.sh
